version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es7112
    environment:
    - cluster.name=springboot-demo
    - node.name=es7112
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.seed_hosts=es7112
    - cluster.initial_master_nodes=es7112
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - es7data:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
volumes:
  es7data:
    driver: local